"""create transaction table

Revision ID: 90592f8bf110
Revises: 1600047f7159
Create Date: 2025-03-02 15:14:32.566121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90592f8bf110'
down_revision = '1600047f7159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('feature_code', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=50, scale=2), nullable=False),
    sa.Column('receiver', sa.String(length=100), nullable=False),
    sa.Column('tnxID', sa.UUID(), nullable=False),
    sa.Column('charge', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tnxID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
